[package]
name = "web-server-tide"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.6.1"
rand="0.3.14"
failure = "0.1.5"
tide = "0.15.0"
async-std = { version = "1.6.5", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.39"